### ISSUE TITLE
Fatal error when running under MariaDB

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pln#90]
The error is happening at the last step, where the plugin does some cleanup (remove not existing issues/deposits), which should be not needed anymore after adding foreign keys to the entities on the +3.4 releases.

Source: https://forum.pkp.sfu.ca/t/pkp-pn-impossible-to-deposit-most-of-our-issues/88989/3

```php
Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'as `do` where `do`.`journal_id` not in (select `j`.`journal_id` from `journal...' at line 1 in /var/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:566
Stack trace:
#0 /var/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(566): PDO->prepare()
#1 /var/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/lib/pkp/lib/vendor/lar...'
```

**Comment by mpbraendle** [comment]
We observed that as well, is produced from APP\plugins\generic\pln\classes\depositObject\DAO->pruneOrphaned()
